export const environment = {
  'SERVER_URL': 'https://final-project-shiqip-1-9b9h.onrender.com/',
  'CKEDITOR_LICENSE': 'eyJhbGciOiJFUzI1NiJ9.eyJleHAiOjE3NDgzMDM5OTksImp0aSI6IjBjZjEyOTJjLWQxMzEtNDRjNC05NzhhLTE4Nzc1ZTE5ODY2NCIsInVzYWdlRW5kcG9pbnQiOiJodHRwczovL3Byb3h5LWV2ZW50LmNrZWRpdG9yLmNvbSIsImRpc3RyaWJ1dGlvbkNoYW5uZWwiOlsiY2xvdWQiLCJkcnVwYWwiLCJzaCJdLCJ3aGl0ZUxhYmVsIjp0cnVlLCJsaWNlbnNlVHlwZSI6InRyaWFsIiwiZmVhdHVyZXMiOlsiKiJdLCJ2YyI6IjRiMTVlYTA4In0.l3wErtbIpsZ48Asuymdd7jh9rdhvTMTbJ9-X3_nfJQ8swfK1HzfqjvrfELGipDNJALWey6o8YH4Nct3-zZLu9w'
};
